CREATE TABLE IF NOT EXISTS `nd_users` (
	`user_id` INT(11) NOT NULL AUTO_INCREMENT,
	`id_steam` LONGTEXT NULL DEFAULT NULL,
	`id_discord` LONGTEXT NULL DEFAULT NULL,
	`id_xbl` LONGTEXT NULL DEFAULT NULL,
	`id_live` LONGTEXT NULL DEFAULT NULL,
	`id_license` LONGTEXT NULL DEFAULT NULL,
	`id_license2` LONGTEXT NULL DEFAULT NULL,
	`id_fivem` LONGTEXT NULL DEFAULT NULL,
	`id_ip` LONGTEXT NULL DEFAULT NULL,
	PRIMARY KEY (`user_id`) USING BTREE
) COLLATE='utf8mb4_unicode_ci';
